### PR TITLE
Cockpit windows

### PR DESCRIPTION
**Pull request by kroki**
Implemented openable cockpit windows (in both internal and external models).  Right now windows may be opened at any altitude.  This should be fixed for windows and doors when we will have implementation for pressurization procedures.

### CODE REVIEW

**Comment by DestroyFX** [comment]
Work fine.

The only thing is that they are open by default when you load the model :)

**Comment by kroki** [comment]
> they are open by default when you load the model :)

This is intentional, as in all YouTube videos windows are initially opened (it seems to be a requirement, since they are opened even if it [rains] (http://www.youtube.com/watch?v=PlzjJH7fonE&t=0m38s); BTW APU is not exactly 100% [there] (http://www.youtube.com/watch?v=PlzjJH7fonE&t=8m52s)).

I just added a patch that closes windows during autostart with 's' key.

**Comment by DestroyFX** [comment]
Good to know! For the APU. A saw picture with it between 98 and about 101% and I did plan to add a random function that decide of a number between 96.75 and 101.25% when you load the model and stick to it until the next time it get loaded.

I got a ton of high res picture we got authorisation to use (to make instruments texture and to replace very low res image for the non-implemented instruments). That also include another +- 90M rar file with high res picture for formation but could not open it because it is not utf8 encoded and none of my unrarer want to deal with it. Where is the best place to dump them, issue or wiki?

**Comment by kroki** [comment]
> I got a ton of high res picture we got authorisation to use

Your source should agree to release the images under GPL.

> Where is the best place to dump them, issue or wiki?

I dunno.  If GitHub wiki allows such big attachments you may place them in your tu154b fork and we will pick them up from there.

**Pull request closed without merging**
