### PR TITLE
Added "hijack" warning light and "2500kg fuel" alarm sound mute switch

### PR DESCRIPTION
**Pull request by OrangeTiger**
ССО опасн - warning light shows up when transponder is set to 7500.
As mentioned below I got this from the "tu154eng.pdf" but I'm not 100% sure if this is how this warning works, because it's very hard to find something about the tu154 in english.

### CODE REVIEW

**Comment by kroki** [comment]
I can't check it in action, I assume you use red light `ССО опасн` ("threat notification system - danger").  But what are your sources?  I.e. what makes you think that this light turns on when transponder set to 7500?  Normally we follow Flight Manual very closely and do not invent things on our own.  For lights there's a doc www.dream-air.ru/new/pilotam/.pdf (note that file has no name, only `.pdf` extension - I had trouble finding it in file system after download).  It's in Russian, but there's little text that you may feed to Google translate.  Re `ССО опасн` it made me thing that this alarm is initiated by fight attendants to warn cockpit crew about hijack threat.  The description of yellow light `ССО связь` ("threat notification system - communication") is not of much help there.

Having said that, we may use one of this lights for 7500 because it's unlikely we'll use them for anything else.

**Comment by kroki** [comment]
Perhaps it's also worth noting that "Added hijack warning" is too vague (yup, I said message is good in e-mail, but I changed my mind :P).  The exact form of such "warning" is not immediate from the patch, so it's better to use a description field above (and/or a commit message itself) to describe what exactly should happen so that everyone else won't have to look for unknown clues, and will be able to confirm that they indeed observe what they were supposed too.

**Comment by OrangeTiger** [comment]
My source for that change was the "tu154eng.pdf" which is delivered with the aircraft in the "Docs" folder. There it says "147 - Lights up when the transponder is set to "hijack" (not used the sim) " and 147 is the ССО опасн warning light. So the international Transponder Code for Hijack is 7500.

**Comment by OrangeTiger** [comment]
You wrote me in the mail, that I can add a description to the commit by leaving a blank line after the commits name and then adding the description.
I uploaded this commit with the linux command line and I'm not sure how to add a blank line to this. Should i Use "\n" or is there any other way?

**Comment by kroki** [comment]
> "147 - Lights up when the transponder is set to "hijack"

I'm pretty sure that's not how it works in real thing, but having it this way in the model won't harm and will at least make the light alive.

> Should i Use "\n" or is there any other way?

For some reason I suspect you use Linux in a virtual machine from Windows (you didn't have to BTW).  Still I assume that you installed Linux with GUI support.  If so I suggest to install `git gui` utility (and also `gitk`).  Linux distributions vary so I can't tell you the exact package name nor the exact command to use to install the package (googling the problem will give you the answer).  Once installed, `git gui` command will open up a window that will allow you to select changes to commit, enther commit message in milti-line text edit field, and commit the changes with a button.  `gitk --all` command will show you the history of all branches.

But if you installed Linux without GUI support, than running `git commit` (i.e. without `-m/--message` option) will start a text editor, which is likely to be `vim`.  There you type `i` to enter "input" mode, enter the text (arrows to navigate, backspace/delete keys for editing), then press `ESC` key to leave "input" mode, and type `:wq` (which stands for "command-write-quit").

**Comment by OrangeTiger** [comment]
No, it's the other way round, I use Windows in a virtual machine. But never the less thanks for the git gui and gitk, I will install these.

**Comment by DestroyFX** [comment]
I have tested the patchs. 

Everything work according the the patch description. Also, I have scanned the documentation for setting the transponder to 7500 but I might just have missed it (I'm not good a Russian and I got 130M of scanned doc that can't be OCRed nor google translated).

**Comment by antage** [comment]
I read this document - http://aviadocs.net/RLE/Tu-154B/CD1/TU/Tu-154B_TU_v14.pdf
The document explains a procedure for checking "ССО опасно" alarm (a lamp and buzzer) .
"ССО опасно" alarm can be activated by any of 3 fake sockets.
Button "СБРОС СИГНАЛА ССО" turns off the alarm.

I didn't find any references to transponder in the document.

**Comment by OrangeTiger** [comment]
Alright so I guess the Documentation https://github.com/yuriknsk/tu154b/blob/master/Docs/tu154eng.pdf is wrong. So can anyone explain how I can undo this commit?

**Comment by kroki** [comment]
You don't have to remove any of the patches.  Just close pull request and move this patch from your `master` branch to some other:
```
git checkout master
git branch hijack-7500-SSO-light
git reset --hard HEAD^
git push --force --all
```
and this patch will be moved from `master` to `hijack-7500-SSO-light` branch.  Maybe someone will pickup your work later.

**Comment by OrangeTiger** [comment]
Ok, I put them both in a new branch.

I will now figure out if I can find any reliable documentation of the Tu-154B-2 in english and see if I can work on anything of that.

**Comment by kroki** [comment]
It's a voluntary work, please don't feel obliged to do anything beyond your comfortable reach.  The work what doesn't require reading Russian and that most of us would like someone else to do :) is to finish 3-D model of engineer panel.  It's possible to do most of it by placing existing elements onto their depicted positions.  But since you added one switch and refused to add another I guess you learned how tedious the process is :)

Also, if you are good with 3-D modeling than we need to finish the transponder: we have [this part] (http://www.avsim.su/forum/uploads/monthly_06_2011/post-2860-0-26726300-1307176503_thumb.jpg) but only a picture for [this] (http://www.avsim.su/forum/uploads/post-2860-1151894946_thumb.jpg) (the latter is BTW where power switch is located).

**Comment by OrangeTiger** [comment]
Yeah it was just a little frustrating that every single patch or fix I made was wrong for now. But I will not give up :)
So I will try on the second part of the transponder you posted me. I guess its is located downright of the part already modeled. Is the location correct there? I will now start modeling the instrument and will look for the function of each button later on.

**Comment by kroki** [comment]
BTW, on [Russian forum] (http://www.flightgear.ru/forum/viewtopic.php?f=9&t=247) we have an artist who may paint the background and add labels once (some part of) engineer panel is ready (and he also speaks German BTW).

More tasks to consider (for you, for DestroyFX, for anyone else):
* Shiny rectangles on [this picture] (http://www.flightgear.ru/forum/download/file.php?id=1397&mode=view) are covers of additional air intakes.  We are missing animation for rotation to open them up (say, 30 degrees).  There are many of them, but once you figure out an axis of rotation for one of them you may assume spherical chickens and use trigonometry to compute other axes.  [This post] (http://www.flightgear.ru/forum/viewtopic.php?f=9&t=247&start=1160#p11286) has a link for Russian docs that are promised to describe when covers open up (though no page number provided).  However as a good first-order approximation you may open them up when throttle is above nominal value (the one set with 'n' key), i.e.:
```
open_angle = 30 * max(0, throttle - nominal_throttle) / (max_throttle - nominal_throttle)
```
* Gear up/gear down control in the model has only two positions and keys: 'g' for up, 'G' for down.  But in real plane there are three states: up, down, and neutral (lever is in the middle position).  Normally the lever in the neutral position and hydraulic valve is closed.  When extending/retracting gears you open a valve and crew controls the process.  Once extended/retracted engineer waits until the pressure in hydraulic system raises back to 205kg/cm2, then he waits for 20 seconds more controlling that there are no hydraulic leaks, and after that commands "gear valve to neutral".  Right now second officer immediately replies with "gear valve set to neutral (see 975c6ac781), but having an explicit key for this (I suggest 'Ctrl-g') would be cool (you'll also have to fix the lever itself).
* We  are missing [refuel panel] (http://c.avsim.su/i?u=http%3A%2F%2Fromadm.users.photofile.ru%2Fphoto%2Fromadm%2F3799390%2Fxlarge%2F88476400.jpg), which is located somewhere under left wing.
* I believe indicators of surface deflections (white lines on black background in the bottom left corner of front middle panel) aren't calibrated properly, some deflect only so slightly.
* Throttle lever positions up to 40 degrees are all idle in the real plane.
* Flight log doesn't record many instruments so during replay they are dead.
* You can't start playing again from arbitrary replay position as they have it in Boeing 777 IIRC.
* Some more, but I'm tired to type ;)  asking on Russian forum will give you plenty :)

> I guess its is located downright of the part already modeled. Is the location correct there?

No, it is more close to airplane's nose.  It looks on the model's texture exactly as it looks on the picture I provided.

**Comment by kroki** [comment]
For the reference:
transponder-main
I think "protocol" selector selects the format of a reply (what subset of altitude, speed, heading, fuel, etc. to transmit and in what form).  In Russia `УВД` ("ATC") is used, in other contries normally set to `RBS`.  I don't know what `ВОЛНА` does (literally "wave", may mean "band" or smth similar).

**Comment by OrangeTiger** [comment]
skawk

I know this is far from being finished, positioning this model is really pain in the ass. But you can see where I'm going to place it and the first 2 knobs (Protocol and Band, or whatever). So the placing there is correct? I just put it above the image of the instrument.

**Comment by kroki** [comment]
Yup, that's the right place.

**Comment by OrangeTiger** [comment]
transponder

This is how far I am with shaping the base of the new Transponder Panel. I'm not really happy with that, because it's getting pretty thin on the end. That's related to the shape of the console and otherwise the Transponder panel would go over the edge. What do you think?

**Comment by kroki** [comment]
The model of the base should not be distorted, i.e. it should be a rectangle (with cut ears).  You don't have to place it exactly above the original trace on texture, our artist will paint the background as needed (if you look at the bottom of ef605873e page you'll notice that we also moved the other part: it used to be in place of a bottom metal plate, but that location is obscured by chair armrest).  So just move it closer to the viewer and a bit closer to the window and it will fit.

I just found a description of a [different transponder model] (http://oleg-tulin.narod.ru/index/0-26).  From it follows that for our purposes `023М` is the same as `УВД` (basically, all protocols are the same for us).  It also says that the test lamp blinks whenever transponder send the reply (we may do this by timer, say every 1 minute).

**Comment by OrangeTiger** [comment]
Ah well, if you have someone who could redraw the side console, I would place the panel like this:
fgfs-screen-001

There it fits with the edge and has the same distance to the steel plate on the left like the other transponder panel. What I would need now is someone, who could draw a "text.png" with the russian text on it in the size 231x76. What is the name of the artist in the russian forum so I could ask him for it.

**Comment by kroki** [comment]
> What is the name of the artist in the russian forum so I could ask him for it.

`git show cd19b000` will reveal his name and e-mail.  As a temporal mean you may resize original transponder picture to use for texture and ask him to draw the same sizes.

**Comment by DestroyFX** [comment]
I can redraw the side console to remove the old transponder panel under your new panel and have it in the Orange branch of my git by this night. I did also clean the section for the 2500kg fuel mute but that one is incorporated with the panel overhaul i'm doing (currently busy making a three position switch based azs1)

**Comment by DestroyFX** [comment]
Ok. I made a change to the vc04 file : https://github.com/DestroyFX/tu154b/commit/591d43dad2a33c3eea70be173b8d43830e1240eb

I could not put it in the OrangeTiger branch because I have a ton of stuff not ready to commit so I put it in my devel branch. You should add my git in remote to your local tree in that way :

$ git remote add destroyfx https://github.com/DestroyFX/tu154b.git (add a remote named destroyfx, you can put the name you want)
$ git fetch destroyfx devel (to download my devel branch, will not overwrite or apair in your stuff)
- After that be sure to be in the branch you want the new console texture
$ git cherry-pick 591d43dad2a33c3eea70be173b8d43830e1240eb

That way you get my texture and when you are ready to merge you can include my commit and it will be a separated patch by me in your pull request. Also I recommend you to cherry-pick my three whitespaces patchs (just don't include them in pull request) if you plan to play in the code more so a pile of conflict don't pile up on the Yurik side when he merge.

**Comment by kroki** [comment]
At a risk of being offensive I'd say that our artist has a better sense or color tone.  Borders are clearly visible on yours.

**Comment by kroki** [comment]
> Edit : I did not have a proper green matter to sample because of the angles/light so it's not that perfect and can be use temporary.

We can live temporarily with the old trace showing through.  Each image commit will add to repo size, so it's better not to add temporal images.  The point is not that you picked the wrong color at a wrong place and used a wrong brush.  The point is that true artist will do much more than picking and brushing.  See how he drew the metal plate at the bottom of ef60587 - you can actually _feel_ the rough surface and ambient light.  That's why I wasn't particularly exited when you started drawing [the panel] (https://cloud.githubusercontent.com/assets/39372/9566233/1bf4d22e-4ec3-11e5-8909-131100e73393.png) instead of filling in a model: your dividing line is obviously thinner and clearly shows aliasing pattern close to where two lines converge into one.

I'm currently listening to the course titled ["No excuses"] (http://www.thegreatcourses.com/courses/no-excuses-existentialism-and-the-meaning-of-life.html).  From the description:

> ...every one of us, as an individual, is responsible—responsible for what we do, responsible for who we are, responsible for the way we face and deal with the world, responsible, ultimately, for the way the world is.

So lets do what we can take responsibility for without any excuses, and let the artist do his part.  I'm particularly good at making other people hate me, and I expect everyone to follow me in doing their best :).

**Comment by DestroyFX** [comment]
@kroki I know and it's why I edited my initial post to mention "temporary". I did made another attempt here: https://github.com/DestroyFX/tu154b/commit/f2b292c6f0fe28bb345741d20e3e3b7fae43edb6 but I can't really do better than that patching it. to many different shade of green to manage :p

**Comment by DestroyFX** [comment]
For the other panel I began to do for the air conditioning section. I stopped to try to improve it and just use my "hole" mask to fit the switch in the proper positions.

**Comment by OrangeTiger** [comment]
I wrote the artist from the russian forum, but unfortunatly hes going on holidays tomorrow. So he will make the background image and the caption for the panel in mid September. I'm going to place the handles on the panel for now and position them excactly, when I have the images from him. The most handles are just copy and paste I guess, but I have to look how to do the Emergency switch with the cover. I think there is no switch like that before.

**Comment by DestroyFX** [comment]
That's not that far and it leave time for me to place the models on the other panel.
The textures I made allowed me to see how it will not fit in the original position so I did not loose my time making it :p

**Pull request closed without merging**
