### PR TITLE
Holding 'm' shows "map case", three more tables, easy addition of new in Nasal/mapcase.nas

### PR DESCRIPTION
**Pull request by kroki**
Hi Yurik,

These three patches were prepared a year ago, but I forgot to create a pull request then 8(.

1: Add three climb/descend tables (prepared by Vitaly) to "map case" (where we keep reference papers).
2: New pages may be added easily by adding paths to .png or .svg files to the list at the top of Nasal/mapcase.nas.
3: Holding 'm' key will take a glance at map case.

They should work, but I didn't test them this time (have no FG setup).  So when you are back please check them before merging: map case should show all the pages and holding 'm' key should show the map case.  Thanks!

### CODE REVIEW

**Comment by DestroyFX** [comment]
I will test this night and give you input about them.

**Comment by DestroyFX** [comment]
* The M hotkey work
* All pages are now blank but the pages count add up for the new pages..
fgfs-screen-008
fgfs-screen-009

**Comment by DestroyFX** [comment]
*The 18.png should be moved in the first patch
*The patch that rename the file and change the way the pages are loaded need to be fixed. Maybe also it is possible to make it like the original version : dynamic, add a random png file from the manuel, name it in the next number and it show. Easier for random people to add custom pages.
fgfs-screen-010

**Comment by DestroyFX** [comment]
I just thought about, do these USSR made doc are actually copyrighted or it's owned by the people?

I have the manuals scan here, I could put beautiful book at the engineer station.. :)

**Comment by kroki** [comment]
OK, I don't know what the problem is.  FG (3.4 from Fedora package, not current from sources) reports on console:

  Nasal runtime error: No such member: new
    at /home/tomash/NOBACKUP/src-external/tu154b/Nasal/mapcase.nas, line 36

yet `canvas.new` seems to be the right method.  I also get many other failures because of "security checks".  I used `--aircraft-dir`, some go away when `FG_AIRCRAFT` env var is used instead.  I'm not going to investigate any further.

> Maybe also it is possible to make it like the original version : dynamic, add a random png file from the manuel, name it in the next number and it show. Easier for random people to add custom pages.

I think the new way with the file list is much better:
* Files may have meaningful names.
* Easy to add file in the middle.
* Possible to refer to the same file multiple times (by default pages are ordered according to flight phases).
* File list opens the door for the dialog to fill it (though I won't work on that).

But as said above, I don't have plans to work on this.

**Comment by kroki** [comment]
I have fixed this patch series for FG 3.4+, should work now.

**Pull request merged**
