### PR TITLE
New fuel subsystem implementation with refuel

### PR DESCRIPTION
**Pull request by kroki**
The fuel subsystem has been rewritten in JSBSim and brought in accordance with aircraft manuals.  Minor bugs have been cleaned but there are no dramatic changes from user perspective apart from refuel panel (accessible with '7' key), which now works.

Quick guide for refuel:

The plane now starts with minimum fuel allowed (12750kg, not counting ballast tank 4 which has 4000kg for start-up payload).

The rules for tank 4 when used as a ballast:
- full (6600kg) if payload weight is less that 11500kg
- 4000kg if payload weight is between 11500kg and 14000kg
- 2000kg if payload weight is between 14000kg and 16000kg
- empty if payload weight is above 16000kg

During refuel the fuel is pumped by external pump, aircraft fuel pumps are not used.  Refuel procedure:
1. provide =27V and ~200V power (APU or ground source)
2. enable fuel meters and ABT. PACX. (auto-consumption logic) - the latter one is required for automatic refuel valve closing
3. switch to refuel panel ('7' key), open the door, enable light, enable master switch at the bottom right corner)
4. selector labels are in tons, `П` means "full"
5. refueling tank 4 is straightforward: set target level with selector and turn on valve switch, wait until green light goes off, turn the switch off (if the light doesn't turn on then the tank already has requested amount)
6. refueling tanks 1, 2, 3 is more complex:
6.1 below 12750kg refuel manually:
6.1.1 first fill tank 1 until full (3300kg)
6.1.2 then fill tanks 2 until 1500kg each
6.1.3 finally fill tanks 3 until 3225kg each (total fuel excluding tank 4 will be 12750kg)
6.2 from 12750kg and up first use automatic refueling to the closest level that is below the target.
6.2.1 I.e. if you need say, 22000kg, select 20 tons and open all valves, then wait until all green lamps go off (ABT. PACX. will close valves once tanks reach their target levels in accordance to consumption program for this amount of fuel).
6.2.2 at engineer panel look what tanks are enabled according to the program (yellow lamps)
6.2.3 open corresponding valves on refuel panel and wait until total fuel in tanks 1, 2, 3 reaches 22 tons, then close all valves, turn off refuel master switch, lights, close the door.

For inspiration: http://www.youtube.com/watch?v=usJShCynoXM&t=1m52s .

### CODE REVIEW

**Comment by kroki** [comment]
@sanhozay, @DestroyFX: guys, I just merged patches above.  They are likely to interfere with your work because in the process of moving fuel subsystem to JSBSim I had to rename all fuel-related properties (they are now under `/fdm/jsbsim/fuel/`).  You will likely have to resolve conflicts during rebase/merge - sorry for this :).  Better to do it sooner than later.  Let me know if I can assist you with the merge (I may even do it for you on request if you provide me with branch names to merge, etc.)

Have a nice merging weekend! :D

**Comment by sanhozay** [comment]
Thanks for the warning. I had a couple of conflicts but no major problems.

The refuelling is a great addition. Perhaps you should think about the initial fuel level though, because such a feature deserves to be used: With 12750kg, there's enough for a 2.5 hour flight, so refuelling isn't required for a lot of casual flights. 

Perhaps you could only fill the sump tank, or save the fuel level of each tank when the sim exits and restore on startup?

**Comment by kroki** [comment]
Alas 12750kg is the minimum allowed by Flight Manual (it ensures proper aircraft balance), so I decided not to set it any lower (it was higher before the change).  Likewise 4000kg in tank 4 is with accordance to default load.

> Perhaps you could only fill the sump tank, or save the fuel level of each tank when the sim exits and restore on startup?

I don't know how to implement this (on Linux (at least for me since 2.0 days) FG always coredumps on exit, so I'm used to press Ctrl-c to "quit" - it won't have a chance to save anything).  Also one may always use "Equipment->Fuel and Payload" dialog to reset the fuel.  But patches are welcome!

**Comment by OrangeTiger** [comment]
Does the fuel in the ballast tank "count" for my fuel calculations? So when I calculate 20t of fuel and I have 4t in the ballast tank I only need 16t more? Or would I fill the whole 20t into tanks 1-3 and 4t additional into the ballast tank?

**Comment by kroki** [comment]
> Does the fuel in the ballast tank "count" for my fuel calculations?

No, ballast tank is excluded.

> Or would I fill the whole 20t into tanks 1-3 and 4t additional into the ballast tank?

This variant is correct.

**Comment by OrangeTiger** [comment]
With this variant my calculated Landing Weight will always be MLW. So when I use a little less fuel than calculated I am above MLW at my destination.

Landing Weight will be always like this:
Empty Weight (54t) + Payload (12t) + Ballast (4t) + Fuel to Alternate (2t) + Reserves (6t) = 78t

**Comment by kroki** [comment]
Can't help that ;).  The manual is clear that ballast fuel is not counted.  It also says that it is forbidden to consume ballast fuel (for that before the flight you turn on switches for pumps for tanks 2,3 (and 1 of course) but not 4, and when 2 is empty you switch to manual consumption (4th switch in a row to off), so that after 3 is empty auto-consumption won't turn to tank 4).  Fuel in tank 4 may only be used when you want to extend flight range or need to rebalance.

In tu154b.xml we have empty weight as 53t (not sure where the figure comes from, other sources suggest 51t for Tu-154B).  Payload+ballast should not exceed 18t according to the manual, so 78-(53+18)=7t for fuel.  Perhaps you have too high reserves.

At any rate fuel and balance should be calculated quite precisely, if miscalculated than burn extra in the air (there's no fuel jettison in Tu-154).

**Comment by OrangeTiger** [comment]
When I empty everything in the Fuel & Payload window the remaining empty weight is exactly 54.320kg. I would guess that 54t is the empty weight of the aircraft and 320kg is the 4 x 80kg cockpit crew.
Maybe the empty weight should be adjusted to 51t (or 51.320kg)

**Comment by kroki** [comment]
Yup, my mistake.  Empty weight is indeed 53+1t (the latter is gears, they are separated to emulate COG shift during extension/retraction).  Yup, 54t doesn't seem correct.

However I finally finished with tasks I planned to do, someone else should check with the docs and create a patch.

**Pull request merged**
