### PR TITLE
Made some cosmetic change

### PR DESCRIPTION
**Pull request by DestroyFX**
Hi,
I watched some Tupolev tu-154b2 start-up procedure on youtube, mostly the 85535 and I found out that the APU dial should reach 100% and not 97%. The constant buzzing sound is present as soon as the power is on (not only when generator is on) and finally, the model hydro electric pump was too weak compared the these I saw so I made them a little stronger.

### CODE REVIEW

**Comment by kroki** [comment]
Hi DestroyFX,

Maybe you'll have a better chance after separating essential parts from numerous whitespace changes that your patch brings along, it's quite hard to see what you have changed for real (GitHub doesn't seem to have a functionality similar to --ignore-space-change option to git).

Re 1: you tie the sound to the battery switch.  While the Flight Manual says the battery should stay on during the flight one still may turn it off once other power sources are online - it's better to make the sound trigger be "OR" between battery and the property it had before.

Re 2: I'm not sure why APU is set to 97%, but I doubt it's 100% all the time in any meteorological conditions (even in http://www.youtube.com/watch?v=ln9E8bQr2hg&t=1m0s that you refer to it looks like 101% to me, and the ticks go way up to 110%), perhaps there are some fluctuations and it's possible that such imprecise setting was meant to give it a realistic look&fill.

Re 3: you mention only electric pump in the comment but actually change the pump driven by 1st engine - this requires explanation and also perhaps calibration using that pump's load (leaving it as-is is also safe ;)).

So: I think 1 requires "OR", vote for 2 to be imprecise (99%? 101%?), and think 3 should not touch the other pump w/o any reason.  But Yurik has the final say.

**Comment by DestroyFX** [comment]
I will look for point 1 & 2.

For 3. If you look correctly, I have about 80 lines between Engine pump 1 and my change but it's only for Electrical pump 1 & 2 (both was setted to 20). This is because my IDE seam to remove all extra spaces and I did not see that before my initial pull request.

**Comment by kroki** [comment]
Yup, I misread the patch, sorry (and I also forgot that there are two electric pump, right).  Now I kinda suspicious why you set different powers, they were the same and perhaps should as the load on hydraulic systems is uniform.  Please recheck this place too.

**Comment by kroki** [comment]
Actually I have a strong belief the powers must be the same as the pumps are to instances of the very same hardware.

**Comment by yuriknsk** [comment]
Hi Tomash & Mathieu!

I read yours conversations, but I'm can not verify patches cause I at
vacation now and can't start model and check.
Sorry, but I will proceed patches late, around 3 weeks.

Thanks for yours works!

**Pull request closed without merging**
