### PR TITLE
Patches by Orange Tiger

### PR DESCRIPTION
**Pull request by IAHM-COL**
Hello,

I've made two minor patches for the tu154b again:
1) DME for RSBN is only operating when RSBN Master Switch is on
2) Spoiler Lever is clickable to set or retract Spoilers

The fixes are already confirmed.

The three files are located at:
tu154b/TODO
tu154b/Nasal/instruments.nas
tu154b/Model/vc.xml

I also changed the TODO file, because it says "Make Spoiler Lever clickable" and I just wrote a "checked" behind that :)

Would be nice if you could upload these changes.

Regards,
OrangeTiger

### CODE REVIEW

**Comment by kroki** [comment]
Just look into the patch and you'll see why it must be rejected ;).

**Comment by FGDATA** [comment]
Maybe Fixed now?
IH-COL

**Comment by kroki** [comment]
Yup, that's much better.  Having two separate patches would be better still, but let's not be picky.

My only worry is what would happen if one first enables RSBN power switch, and then provides power.  Can't test this myself, but RSBN DME may not come alive then.  Otherwise looks good.

In private discussion with OrangeTiger I suggested to swap mouse buttons so that one won't extend spoilers by accident with left mouse button (and the version he showed me didn't bind to mouse wheel).  But he objected that flaps handle works the same way, to which I have nothing to oppose.  I agree that there are many places you can click by accident with disastrous effect, so let's leave it as-is.

**Comment by IAHM-COL** [comment]
good :d
Thanks for revising :)

IH-COL

**Comment by OrangeTiger** [comment]
I tested first truning on RSBN first and then activating the power and the DME works.
The only problem I realized with that was the Sound "VOR is in range" (that beeps) has come before power was provided.

**Comment by FGDATA** [comment]
Hi All
@OrangeTiger sent me more pathces, now added with https://github.com/IAHM-COL/tu154b/commit/6b0cb3135ae7a1df2fa3b7b53c34b1d9afc9f811 to this pull request

Best,
IH-COL

**Comment by kroki** [comment]
OrangeTiger, for the record: just checked with [this source] (http://kipmea.kai.ru/files/2014/02/%D0%9C%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-%D0%A2%D1%83-154-%D1%80%D0%B0%D0%B4%D0%B8%D0%BE%D0%BE%D0%B1%D0%BE%D1%80%D1%83%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D0%B0%D0%BC%D0%BE%D0%BB%D0%B5%D1%82%D0%B0.pdf) (in Russian): the switch picture on transponder you are turning into 3-D model with your last patch is not a power switch.  It is labeled `МЧ` ("low sensitivity"), and according to the docs it makes receiver less sensible to queries when close to the radar (this may be requested from the ground).  I think we may make it a power switch.

**Comment by kroki** [comment]
When you run out of ideas you may implement the following: when remaining fuel reaches 2500kg a red light `Остаток 2500` ("remaining fuel 2500kg") starts to flash on pilot's panels and a sound alarm turns on.  In the model the sound alarm goes off after 15 seconds (see 1bd1f9865), but in real plane it is disabled by the switch with the red cover shown below (the light continues to flash):
fuel2500
For aesthetics reasons it will be better to also add the model for the switch above (covers should open in opposite directions), though I don't recall what it does (people on Russian forum may know).

**Comment by OrangeTiger** [comment]
Yeah alright sound like something I could try on, thanks for that.

**Comment by OrangeTiger** [comment]
I only added the mute switch for now. I will maybe do the one above if I know what it's function is.
https://github.com/OrangeTiger/tu154b/commit/fc04643de15ba9e670ec23c831246ce1c2040dec

**Comment by kroki** [comment]
He-he, it seems I've made a mistake.  I was unable to find a good picture of this part of a panel for Tu-154B-2, but for Tu-154M the mute switch is the one with a greenish cover, and Tu-154M has something else (or nothing at all depending on modification) in place of a switch with the red cover that I pointed to ([screenshot] (http://www.avsim.su/file_images/43/img29705_1.jpg) from MSFS).  Sorry for mixup.

**Comment by OrangeTiger** [comment]
On this http://jetphotos.net/viewphoto.php?id=6212202 picture, which shows a Tu-155B-2 there is a switch without the red cover. If the function of the switch is correctly it wouldn't be that much of a problem to "remove" the cover.

**Comment by kroki** [comment]
On that picture labels look to be in Finnish or smth, but no matter how I
look I don't see 2500 on either.

On our texture the switch has a cover.

I suggest adding a switch above red one and making it an alarm mute.
29.08.2015 12:45 пользователь "OrangeTiger" <notifications@github.com>
написал:

**Comment by OrangeTiger** [comment]
I would guess the labels are in hungarian. So can you tell me how to undo a commit? It seems I have to do it with both, the alarm mute and the transponder hijack.
I think it doesn't really make sense for me to develop on the tu154b, becuse I cannot find any reliable documentation in english (or german). So I can read kyrillic alphabet, but I just understand like 10 russian words.

**Comment by FGDATA** [comment]
To undo a commit in the best and clean manner, I suggest you use git revert

          git revert <commitSHA1>

**Comment by DestroyFX** [comment]
On the linked 154m panel you clearly see the 2500 at the "green" top switch while the red switch has been replaced by a rotating button. I can't read the marking at that red button.

http://cdn-www.airliners.net/aviation-photos/photos/2/0/2/1761202.jpg

**Comment by kroki** [comment]
The problem is that once modification is different you can't tell for sure if it's the bottom switch missing, or the top one and the bottom is moved in its place (I too think the top switch is the same (contrary to what I said here at first), though on our texture I can't make "2500" no matter how I look).  The red "button" on the picture is actually a fuse, i.e. a replaceable circuit breaker (it may or may not serve the same function as the red-covered switch in our B-2).

**Comment by kroki** [comment]
I think this request should be closed, as it mixed to many unrelated stuff.  The model for `МЧ` switch will probably appear in the new transponder panel patch set, and clickable spoiler lever should go in separate pull request.

**Pull request closed without merging**
