### PR TITLE
Some cleanup and basic cosmetic change

### PR DESCRIPTION
**Pull request by DestroyFX**
Hi!

I re made my patches so...
1,2,3 - The three first one are useless spaces removing

4 - I changed the API dial so it go up to 100% instead of 97% (like in some Tupolev 154 startup video on youtube)

5 - Changed the pressure of both electrical hydro pumps according to there current rating. NS-46 = 0.05 kgf/cm2 - 0.45 kgf/cm2 (4.90kPa - 44.12kPa)

6 - Changed the condition for the el_loop buzzing sound. Now it's on when the plane is powered by batteries or generator as in the Tupolev video I looked, that sound happens when you turn the batteries ON.

### CODE REVIEW

**Comment by kroki** [comment]
Good, OK to merge.

I trust that first three are whitespace-only as promised (I don't have tu154b repo locally to check with local git, wrote to GitHub people requesting a button for --ignore-space-change).  I also agree with 100% APU figure now: as far as video quality and viewing angle allow to say a number of youtube videos show 100% indeed.

**Comment by kroki** [comment]
FYI: re whitespace button GitHub people replied with:

> There's a "secret" method of doing this, by adding "?w=1" to the URL
> https://github.com/blog/967-github-secrets
> We're considering how to make it more accessible.

Verified first three patches with it, nice!

**Comment by kroki** [comment]
DestroyFX, I think two last image commits do not belong here and should be removed before this request can be merged.

**Comment by DestroyFX** [comment]
Oh i see. Did not know that pushing after a pull request will add to it... I is possible to remove them without leaving revert trail?  Or I have to cherrypick the patchs in a new branch and redo the pull request?

**Comment by kroki** [comment]
Yup, it's better not to leave the revert trail.  Hmm, the only way I can think of is indeed redoing a pull request, the trick suggested [here] (https://github.com/yuriknsk/tu154b/pull/27#issuecomment-135972332), while cleaning up OrangeTiger's local master, didn't affect his pull request.

**Comment by DestroyFX** [comment]
Done, without making a new one. Just got to do:

git stash save "stuff"
git reset --hard HEAD~2 (to go back two commit)
git push --force --all
git stash pop

I should probably not have put the "--all"  as I now have a kroki and OrangeTiger branch on my git I have to remove.

**Pull request merged**
